### ISSUE TITLE
autocomplete-python-jedi

### ISSUE THREAD

**Issue by serafeimgr** [brennv/autocomplete-python-jedi#18]
Hello,

I recently discovered the discussions about autocomplete-python and kite etc.
So in effort to support this fork, i replaced autocomplete-python with autocomplete-python-jedi in pythonic-atom. ( A pythonic packages installer) https://atom.io/packages/pythonic-atom

If you have any other packages in mind that i should include please let me know.

Kind Regards,
Serafeim

**Comment by brennv** [comment]
Cool project, I added an issue here:
https://github.com/serafeimgr/pythonic-atom/issues/2
