### ISSUE TITLE
Disables Ctrl+x, Ctrl+c, Ctrl+v

### ISSUE THREAD

**Issue by ZuluagaSD** [brennv/autocomplete-python-jedi#5]
When I installed this package I no longer have the ability to use the normal copy and paste commands.

Working on Widnows 7, Atom 1.18 x64.

**Comment by brennv** [comment]
Could you try restarting Atom or starting in safe mode?
`atom --safe`

I am looking into similiar issues reported here: 
https://discuss.atom.io/t/is-paste-broken-or-am-i-dumb/11407/33

**Comment by brennv** [comment]
The issue likely revolves around the removal of `install-flow` shown here:
https://github.com/brennv/autocomplete-python-jedi/commit/6706c9933cbe7de258fa7bfc4b329c13ecdc5c3f#diff-b25905eb7879b10fbd8dc9d47d6d0945
https://github.com/brennv/autocomplete-python-jedi/commit/6706c9933cbe7de258fa7bfc4b329c13ecdc5c3f#diff-2fdc12915f59b1e723ca2394d3b1a4f1

**Comment by brennv** [comment]
Ok I think we can fix this by renaming `styles/autocomplete-python.less`, cutting a new release...

**Comment by ZuluagaSD** [comment]
If I disable the plugin I'm able to use the commands again, same if I start in safe mode.

**Comment by brennv** [comment]
@ZuluagaSD Could you try reinstalling or updating to the new release? v1.9.1-2

**Comment by ZuluagaSD** [comment]
Just did, doesn´t work either.

**Comment by brennv** [comment]
Thanks for trying, looking into the `install-flow` workflow...

**Comment by ZuluagaSD** [comment]
No, Thank you for doing this! ;)

Let me know if I need to try something else.

**Comment by brennv** [comment]
While we sort this out it sounds like some folks are using `Cntrl+Insert` and `Shift+Insert`, not ideal.

**Comment by brennv** [comment]
Prepping a package to remove this from keymaps:
```
'.platform-win32':
    'ctrl-c': 'native!'
    'ctrl-x': 'native!'
    'ctrl-v': 'native!'
```
Looking at it again it seems it was put in place to avoid a conflict with the extra installer.

**Comment by brennv** [comment]
@ZuluagaSD v1.9.1-3 is out and ready for testing with the windows patch removed.

**Comment by ghost** [comment]
Same bug with linux too, I'm on v 1.9.1-3

**Comment by brennv** [comment]
Thanks @ormung, sounds like we need to remove the copy/paste remapping for linux too, the macos remapping seems extraneous at this point as well.

**Comment by brennv** [comment]
It sounds like it's working in windows now, prepping the linux patch.

**Comment by brennv** [comment]
@ormung v1.9.1-4 is out with the linux patch, thanks again.

**Comment by ghost** [comment]
Perfect with version -4 on linux, thank'you!

**Comment by ZuluagaSD** [comment]
Can confirm that it is working on Windows.

**Comment by brennv** [comment]
Thanks @ZuluagaSD @ormung, closing this. We'll remove the seemingly extraneous macos lines during the next cleanup.
